///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CatModelCatLocal {
/*
{
  "name": "XYZ",
  "price": 100,
  "instock": true,
  "count": 0,
  "localCount": 0
} 
*/

  String? name;
  int? price;
  bool? instock;
  int? count;
  int? localCount;

  CatModelCatLocal({
    this.name,
    this.price,
    this.instock,
    this.count,
    this.localCount,
  });
  CatModelCatLocal.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    price = json['price']?.toInt();
    instock = json['instock'];
    count = json['count']?.toInt();
    localCount = json['localCount']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['price'] = price;
    data['instock'] = instock;
    data['count'] = count;
    data['localCount'] = localCount;
    return data;
  }
}
