///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CatModelCat {
/*
{
  "name": "XYZ",
  "price": 100,
  "instock": true,
  "count": 0
} 
*/

  String? name;
  int? price;
  bool? instock;
  int? count;

  CatModelCat({
    this.name,
    this.price,
    this.instock,
    this.count,
  });
  CatModelCat.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    price = json['price']?.toInt();
    instock = json['instock'];
    count = json['count']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['price'] = price;
    data['instock'] = instock;
    data['count'] = count;
    return data;
  }
}

class CatModel {
/*
{
  "name": "Popular items",
  "isView": false,
  "cat": [
    {
      "name": "XYZ",
      "price": 100,
      "instock": true,
      "count": 0
    }
  ]
}
*/

  String? name;
  bool? isView;
  List<CatModelCat>? cat;

  CatModel({
    this.name,
    this.isView,
    this.cat,
  });
  CatModel.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    isView = json['isView'];
    if(isView==null){
      isView=false;
    }
    if (json['cat'] != null) {
      final v = json['cat'];
      final arr0 = <CatModelCat>[];
      v.forEach((v) {
        arr0.add(CatModelCat.fromJson(v));
      });
      cat = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['isView'] = isView;
    if (cat != null) {
      final v = cat;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['cat'] = arr0;
    }
    return data;
  }
}
